### ISSUE TITLE
Unable to compile on Ubuntu 12.04 - ‘CAstYield’ was not declared in this scope

### ISSUE THREAD

**Issue by GoogleCodeExporter** [charx0r/pyv8#168]
```
What steps will reproduce the problem?
1. svn checkout v8
2. svn checkout pyv8
3. building v8 succeeds
4. for some reason, python 3.2 can't get V8_HOME env variable - editing the 
source of setup.py and hardcoding it solves that step
5. sudo python3.2 setup.py install

gcc hangs on src/AST.h:
-----------------------
In file included from src/Engine.cpp:14:0:

src/AST.h: In member function ‘virtual void 
CAstVisitor::VisitYield(v8::internal::Yield*)’:

src/AST.h:739:3: error: ‘CAstYield’ was not declared in this scope

src/AST.h: In member function ‘virtual void 
CAstObjectCollector::VisitYield(v8::internal::Yield*)’:

src/AST.h:755:3: error: ‘CAstYield’ was not declared in this scope

src/AST.h: In member function ‘virtual void 
CAstListCollector::VisitYield(v8::internal::Yield*)’:

src/AST.h:782:3: error: ‘CAstYield’ was not declared in this scope
-----------------------

What is the expected output? What do you see instead?
I expect it to finish happily and to be able to use PyV8. Instead I see two 
hours of frustration behind me.

What version of the product are you using? On what operating system?
PyV8 r509

Please provide any additional information below.

```

Original issue reported on code.google.com by `sans.ran...@gmail.com` on 4 Apr 2013 at 5:49

**Comment by GoogleCodeExporter** [comment]
```
Additional info:

$ gcc --version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

libboost version: 1.46.1

Python version: 3.2.3

```

Original comment by `sans.ran...@gmail.com` on 5 Apr 2013 at 2:33

**Comment by GoogleCodeExporter** [comment]
```
fix the API change issue, please verify with SVN trunk code 
```

Original comment by `flier...@gmail.com` on 5 Apr 2013 at 2:46
- Changed state: **Fixed**
- Added labels: **OpSys-All**

**Comment by GoogleCodeExporter** [comment]
```
Thank you, it's fixed now, compilation runs smooth. Although I do get an error 
when I try to import PyV8 package in Python 3.2:
---------------------------
>>> import PyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PyV8.py", line 1081
    var_unicode = u'unicode'
                           ^
SyntaxError: invalid syntax
---------------------------

It works in 2.7 (which is fine, I can do with 2.7). Maybe it has something to 
do with Python 2.7 being symlinked to python, and that one being used while 
building v8?

```

Original comment by `sans.ran...@gmail.com` on 6 Apr 2013 at 12:27
